"""m

Revision ID: 785bd3107462
Revises: e2883da4b645
Create Date: 2023-06-26 14:55:29.213737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785bd3107462'
down_revision = 'e2883da4b645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hiked_trails', schema=None) as batch_op:
        batch_op.alter_column('trail_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hiked_trails', schema=None) as batch_op:
        batch_op.alter_column('trail_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
