"""added image and bio to adventurer

Revision ID: a49f3ba0af21
Revises: debd0781f057
Create Date: 2023-06-27 10:49:50.136040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a49f3ba0af21'
down_revision = 'debd0781f057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventurers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventurers', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
