"""m

Revision ID: debd0781f057
Revises: 785bd3107462
Create Date: 2023-06-27 10:06:37.649744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debd0781f057'
down_revision = '785bd3107462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hiked_trails', schema=None) as batch_op:
        batch_op.alter_column('adventurer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('trails', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trails', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('hiked_trails', schema=None) as batch_op:
        batch_op.alter_column('adventurer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
